# Copyright 2017, 2018, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Run: 
#      $ docker build -t store/oracle/weblogic:12.2.1.3-strace . 
#
# Pull base image
# From the Docker store
# -------------------------
FROM store/oracle/weblogic:12.2.1.3

COPY strace /usr/bin
